apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: test
spec:
  owner: default/siredmar
  targets:
    - ./devices/*/catalog-info.yaml
    - ./networks/*/catalog-info.yaml
    - ./applications/*/catalog-info.yaml
    - ./releases/*/catalog-info.yaml
    - ./releases/rollouts/*/catalog-info.yaml
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: test
  description: This system contains all components for a EdgeFarm
  tags:
    - edgefarm
    - project
  annotations:
    'edgefarm.io/cluster': default
    'edgefarm.io/repo': github.com?owner=siredmar&repo=myrepo
spec:
  lifecycle: production
  owner: default/siredmar
